# Generated by Django 2.1.1 on 2018-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='courseid',
            field=models.CharField(max_length=20),
        ),
    ]
